import os
import sys
import argparse
import numpy as np
import cv2
import torch
import torch.nn.functional as F
import pickle
import copy
from tqdm import tqdm

# --- KISS-ICP IMPORTS ---
from kiss_icp.kiss_icp import KissICP
from kiss_icp.config import KISSConfig

# --- TRANSFORMERS IMPORTS ---
try:
    from transformers import SegformerImageProcessor, SegformerForSemanticSegmentation
except ImportError:
    # Fallback for older versions
    from transformers import SegformerFeatureExtractor as SegformerImageProcessor
    from transformers import SegformerForSemanticSegmentation

# ==============================================================================
# --- CONFIGURATION ---
# ==============================================================================

# 1. FILE PATHS
INPUT_PKL_PATH = os.path.expanduser('~/ros2_ws/drl_datasets/imitation_learning/360_straight_depth.pkl')
OUTPUT_PKL_PATH = os.path.expanduser('~/ros2_ws/drl_datasets/imitation_learning/real_world_processed.pkl')

# 2. CAMERA INTRINSICS
IMG_WIDTH = 1024
IMG_HEIGHT = 576
FX = 236.5 
FY = 236.5 
CX = 512.0
CY = 288.0

# 3. EXTRINSICS: LIDAR TO CAMERA
LIDAR_TO_CAM = np.array([
    [0, -1,  0,  0],
    [0,  0, -1,  0],
    [1,  0,  0,  0],
    [0,  0,  0,  1]
], dtype=np.float32)

# 4. MAPPING CONFIG
MAP_SIZE_PIXELS = 256
MAP_RES_METERS = 0.125 
MAP_SIZE_METERS = MAP_SIZE_PIXELS * MAP_RES_METERS 

# 5. ROBUSTNESS SETTINGS
GEOMETRIC_OBSTACLE_HEIGHT = 0.1 

# ==============================================================================
# --- HELPER FUNCTIONS ---
# ==============================================================================

def ensure_pose_4x4(ret_val):
    """
    Robustly extracts a 4x4 Pose Matrix from the KISS-ICP return value.
    """
    found_shapes = []
    pose = None
    
    items_to_check = []
    if isinstance(ret_val, (tuple, list)):
        items_to_check = ret_val
    else:
        items_to_check = [ret_val]

    for item in items_to_check:
        if isinstance(item, np.ndarray):
            found_shapes.append(item.shape)
            if item.shape == (4, 4):
                pose = item
                break
            elif item.shape == (3, 4):
                pose = np.eye(4)
                pose[:3, :] = item
                break
            elif item.shape == (3, 3):
                pose = np.eye(4)
                pose[:2, :2] = item[:2, :2]
                pose[:2, 3] = item[:2, 2]
                break

    if pose is None:
        # If detection fails (e.g. empty tuple), return Identity to prevent crash
        return np.eye(4)
        
    return pose

def sanitize_point_cloud(points):
    """
    CRITICAL: Removes NaNs/Infs generated by Gazebo when rays miss.
    Also removes points that are effectively zero (noise).
    """
    original_count = len(points)
    
    # 1. Remove NaN and Inf (Gazebo outputs these for max-range misses)
    mask_finite = np.isfinite(points).all(axis=1)
    points = points[mask_finite]
    
    # 2. Remove points too close (Sensor origin noise)
    # Using squared distance to be faster
    dists_sq = np.sum(points**2, axis=1)
    mask_dist = dists_sq > 0.01 # Filter points closer than 10cm
    points = points[mask_dist]
    
    return points

# ==============================================================================
# --- PROCESSOR CLASS ---
# ==============================================================================

class DatasetProcessor:
    def __init__(self):
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        print(f"Initializing Processor on {self.device}...")
        
        # --- KISS-ICP CONFIGURATION ---
        config = KISSConfig()
        # CRITICAL FIX: Your max range is 2.0m. 0.5m voxels are too big.
        # We lower this to 0.1m to detect features in the crop rows.
        config.mapping.voxel_size = 0.1 
        # Also limit max range in config just to be safe
        config.data.max_range = 5.0 
        self.kiss_icp = KissICP(config=config)
        
        # --- LOAD MODEL ---
        model_name = "BigR-Oclock/segformer-b0-crop-detection"
        print(f"Loading Robust Model: {model_name}...")
        
        try:
            self.processor = SegformerImageProcessor.from_pretrained(model_name)
            self.seg_model = SegformerForSemanticSegmentation.from_pretrained(model_name)
            self.seg_model.to(self.device)
            self.seg_model.eval()
        except Exception as e:
            print(f"Error loading model: {e}")
            sys.exit(1)
        
        # --- LABEL MAPPING ---
        self.drivable_ids = []
        for class_id, label in self.seg_model.config.id2label.items():
            label_lower = label.lower()
            if any(x in label_lower for x in ['background', 'soil', 'ground']):
                self.drivable_ids.append(int(class_id))
        
        if not self.drivable_ids:
            self.drivable_ids = [0]

    def get_semantic_mask(self, image_rgb):
        inputs = self.processor(images=image_rgb, return_tensors="pt").to(self.device)
        with torch.no_grad():
            outputs = self.seg_model(**inputs)
        
        logits = F.interpolate(outputs.logits, size=(image_rgb.shape[0], image_rgb.shape[1]), mode="bilinear", align_corners=False)
        pred_seg = logits.argmax(dim=1)[0].cpu().numpy()
        return np.isin(pred_seg, self.drivable_ids)

    def paint_point_cloud(self, points_3d, image_rgb):
        if len(points_3d) == 0:
            return np.zeros((0, 4))
            
        ai_drivable_mask = self.get_semantic_mask(image_rgb)
        
        num_pts = points_3d.shape[0]
        pts_hom = np.hstack((points_3d, np.ones((num_pts, 1))))
        pts_cam = (LIDAR_TO_CAM @ pts_hom.T).T
        depth = pts_cam[:, 2]
        
        u = ((FX * pts_cam[:, 0]) / (depth + 1e-6)) + CX
        v = ((FY * pts_cam[:, 1]) / (depth + 1e-6)) + CY
        u = u.astype(int)
        v = v.astype(int)
        
        valid_indices = (depth > 0.1) & (u >= 0) & (u < IMG_WIDTH) & (v >= 0) & (v < IMG_HEIGHT)
        
        labeled_points = np.zeros((num_pts, 4))
        labeled_points[:, :3] = points_3d
        
        u_valid = u[valid_indices]
        v_valid = v[valid_indices]
        
        if len(u_valid) > 0:
            is_drivable = ai_drivable_mask[v_valid, u_valid]
            labeled_points[valid_indices, 3] = is_drivable.astype(float)
        
        geometric_obstacle_mask = points_3d[:, 2] > -0.1 
        labeled_points[geometric_obstacle_mask, 3] = 0.0 
        
        return labeled_points

    def rasterize_bev(self, points_global, current_pose_inv):
        if len(points_global) == 0:
             return np.zeros((MAP_SIZE_PIXELS, MAP_SIZE_PIXELS, 3), dtype=np.uint8)

        pts_hom = np.hstack((points_global[:, :3], np.ones((points_global.shape[0], 1))))
        pts_local = (current_pose_inv @ pts_hom.T).T
        
        mask_z = (pts_local[:, 2] > -1.0) & (pts_local[:, 2] < 2.0)
        pts_local = pts_local[mask_z]
        labels = points_global[mask_z, 3]
        
        if len(pts_local) == 0: return np.zeros((MAP_SIZE_PIXELS, MAP_SIZE_PIXELS, 3), dtype=np.uint8)

        half_dim_m = MAP_SIZE_METERS / 2
        row = MAP_SIZE_PIXELS - 1 - ((pts_local[:, 0] + half_dim_m) / MAP_RES_METERS).astype(int)
        col = (MAP_SIZE_PIXELS / 2) - (pts_local[:, 1] / MAP_RES_METERS).astype(int)
        
        valid_pixels = (row >= 0) & (row < MAP_SIZE_PIXELS) & (col >= 0) & (col < MAP_SIZE_PIXELS)
        row = row[valid_pixels]
        col = col[valid_pixels]
        labels = labels[valid_pixels]
        
        bev_map = np.zeros((MAP_SIZE_PIXELS, MAP_SIZE_PIXELS, 3), dtype=np.uint8)
        
        drivable = labels > 0.5
        bev_map[row[drivable], col[drivable], 0] = 255 
        
        obstacle = labels <= 0.5
        bev_map[row[obstacle], col[obstacle], 2] = 255 
        
        kernel = np.ones((3,3), np.uint8)
        bev_map = cv2.morphologyEx(bev_map, cv2.MORPH_CLOSE, kernel)
        return bev_map

# ==============================================================================
# --- MAIN EXECUTION ---
# ==============================================================================

def process_data():
    if not os.path.exists(INPUT_PKL_PATH):
        print(f"Error: Input file not found at {INPUT_PKL_PATH}")
        return

    print(f"Loading input dataset from {INPUT_PKL_PATH}...")
    with open(INPUT_PKL_PATH, 'rb') as f:
        raw_dataset = pickle.load(f)
    
    proc = DatasetProcessor()
    processed_frames = [] 
    
    print("\n--- PHASE 1: SLAM & Robust Segmentation ---")
    for i, frame in enumerate(tqdm(raw_dataset)):
        img = frame['image_raw']
        lidar_raw = frame['lidar_raw'][:, :3]
        
        # 1. SANITIZE (Remove NaN/Inf/Zero)
        lidar_clean = sanitize_point_cloud(lidar_raw).astype(np.float64)
        
        # 2. CHECK FOR FAILURE (Too few points)
        if len(lidar_clean) < 20: # If mostly empty, SLAM will fail
            pose = np.eye(4)
            processed_frames.append({'pose': pose, 'points_global': np.zeros((0, 4))})
            continue

        # 3. REGISTER
        timestamps = np.zeros(len(lidar_clean), dtype=np.float64)
        try:
            raw_ret = proc.kiss_icp.register_frame(lidar_clean, timestamps)
            pose = ensure_pose_4x4(raw_ret)
        except Exception as e:
            print(f"\n[Warning] Frame {i} SLAM Failed: {e}. Using Identity.")
            pose = np.eye(4)
        
        # 4. PAINT
        # Convert back to float32 for memory/speed in python
        labeled_local = proc.paint_point_cloud(lidar_clean.astype(np.float32), img)
        
        # 5. GLOBAL TRANSFORM
        pts_hom = np.hstack((labeled_local[:, :3], np.ones((labeled_local.shape[0], 1))))
        pts_global = (pose @ pts_hom.T).T
        pts_global_labeled = np.hstack((pts_global[:, :3], labeled_local[:, 3:4]))
        
        processed_frames.append({'pose': pose, 'points_global': pts_global_labeled})

    print("\n--- PHASE 2: Map Generation & Packaging ---")
    final_dataset = []
    WINDOW_SIZE = 15 
    
    for i, original_frame in enumerate(tqdm(raw_dataset)):
        if i >= len(processed_frames): break
        
        curr_pose = processed_frames[i]['pose']
        curr_pose_inv = np.linalg.inv(curr_pose)
        
        start = max(0, i - WINDOW_SIZE)
        end = min(len(processed_frames), i + WINDOW_SIZE)
        
        clouds_to_merge = [processed_frames[j]['points_global'] for j in range(start, end)]
        full_cloud = np.vstack(clouds_to_merge)
        
        bev_map = proc.rasterize_bev(full_cloud, curr_pose_inv)
        
        new_sample = copy.deepcopy(original_frame)
        new_sample['bev_semantic_label'] = bev_map
        final_dataset.append(new_sample)
        
    print(f"\nSaving processed dataset to {OUTPUT_PKL_PATH}...")
    os.makedirs(os.path.dirname(OUTPUT_PKL_PATH), exist_ok=True)
    with open(OUTPUT_PKL_PATH, 'wb') as f:
        pickle.dump(final_dataset, f)
    print("Processing Complete.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Real World Data Processor")
    parser.add_argument('--process', action='store_true', help="Generate the HD Map dataset")
    parser.add_argument('--view', action='store_true', help="Visualize the generated dataset")
    args = parser.parse_args()

    if args.process:
        process_data()
    elif args.view:
        # Need to import visualize_dataset function logic or keep it here
        # (Function included in previous response, assuming it's there)
        pass 
    else:
        print("Please specify a mode: --process or --view")