<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="car_robot">

    <!-- ======================= PROPERTIES ======================= -->
    <xacro:property name="chassis_length" value="0.3"/>
    <xacro:property name="chassis_width" value="0.3"/>
    <xacro:property name="chassis_height" value="0.1"/>
    <xacro:property name="wheel_separation" value="0.25"/>
    <xacro:property name="wheel_base" value="0.25"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_diameter" value="${2 * wheel_radius}"/>
    <xacro:property name="PI" value="3.1415926535897931"/>

    <!-- ======================= ROBOT STRUCTURE (LINKS/JOINTS) ======================= -->
    <!-- Base -->
    <link name="base_footprint"/>
    <link name="base_link">
        <visual><geometry><box size="${chassis_length} ${chassis_width} ${chassis_height}"/></geometry></visual>
        <collision><geometry><box size="${chassis_length} ${chassis_width} ${chassis_height}"/></geometry></collision>
        <inertial><mass value="5.0"/><inertia ixx="0.039" ixy="0" ixz="0" iyy="0.039" iyz="0" izz="0.075"/></inertial>
    </link>
    <joint name="base_footprint_joint" type="fixed"><parent link="base_footprint"/><child link="base_link"/><origin xyz="0 0 ${wheel_radius + chassis_height/2}"/></joint>

    <!-- Steering Assembly (Hinge + Wheel) -->
    <!-- THIS IS YOUR ORIGINAL, WORKING MACRO -->
    <xacro:macro name="steering_wheel" params="prefix side side_y_reflect">
        <link name="${prefix}_${side}_steering_hinge_link"/>
        <joint name="${prefix}_${side}_steering_joint" type="revolute"><parent link="base_link"/><child link="${prefix}_${side}_steering_hinge_link"/><origin xyz="${wheel_base/2} ${side_y_reflect*wheel_separation/2} 0"/><axis xyz="0 0 1"/><limit effort="10" velocity="1.0" lower="-0.6" upper="0.6"/></joint>
        <link name="${prefix}_${side}_wheel_link"><visual><origin rpy="${PI/2} 0 0"/><geometry><cylinder radius="${wheel_radius}" length="0.05"/></geometry></visual><collision><origin rpy="${PI/2} 0 0"/><geometry><cylinder radius="${wheel_radius}" length="0.05"/></geometry></collision><inertial><mass value="0.5"/><inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/></inertial></link>
        <joint name="${prefix}_${side}_wheel_joint" type="continuous"><parent link="${prefix}_${side}_steering_hinge_link"/><child link="${prefix}_${side}_wheel_link"/><axis xyz="0 1 0"/></joint>
    </xacro:macro>

    <!-- Rear Wheel Assembly -->
    <!-- THIS IS YOUR ORIGINAL, WORKING MACRO -->
    <xacro:macro name="drive_wheel" params="prefix side side_y_reflect">
        <link name="${prefix}_${side}_wheel_link"><visual><origin rpy="${PI/2} 0 0"/><geometry><cylinder radius="${wheel_radius}" length="0.05"/></geometry></visual><collision><origin rpy="${PI/2} 0 0"/><geometry><cylinder radius="${wheel_radius}" length="0.05"/></geometry></collision><inertial><mass value="0.5"/><inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/></inertial></link>
        <joint name="${prefix}_${side}_wheel_joint" type="continuous"><parent link="base_link"/><child link="${prefix}_${side}_wheel_link"/><origin xyz="-${wheel_base/2} ${side_y_reflect*wheel_separation/2} 0"/><axis xyz="0 1 0"/></joint>
    </xacro:macro>

    <xacro:steering_wheel prefix="front" side="left"  side_y_reflect="1" />
    <xacro:steering_wheel prefix="front" side="right" side_y_reflect="-1"/>
    <xacro:drive_wheel   prefix="rear"  side="left"  side_y_reflect="1" />
    <xacro:drive_wheel   prefix="rear"  side="right" side_y_reflect="-1"/>

    <!-- Lidar -->
    <link name="laser_link"/>
    <joint name="laser_joint" type="fixed"><parent link="base_link"/><child link="laser_link"/><origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/></joint>

    <!-- ======================= GAZEBO PLUGINS AND PROPERTIES ======================= -->
    <!-- THIS IS THE FULLY CORRECTED PLUGIN BLOCK FOR YOUR ORIGINAL MACROS -->
    <gazebo>
        <plugin name="gazebo_ros_ackermann_drive" filename="libgazebo_ros_ackermann_drive.so">
            <ros>
                <remapping>cmd_vel:=/cmd_vel</remapping>
                <remapping>odom:=/odom</remapping>
            </ros>
            
            <!-- These names now correctly match the names generated by your original macros -->
            <left_steering_joint>front_left_steering_joint</left_steering_joint>
            <right_steering_joint>front_right_steering_joint</right_steering_joint>
            
            <left_front_wheel_joint>front_left_wheel_joint</left_front_wheel_joint>
            <right_front_wheel_joint>front_right_wheel_joint</right_front_wheel_joint>
            
            <left_rear_wheel_joint>rear_left_wheel_joint</left_rear_wheel_joint>
            <right_rear_wheel_joint>rear_right_wheel_joint</right_rear_wheel_joint>
            
            <!-- Kinematics -->
            <wheel_separation>${wheel_separation}</wheel_separation>
            <wheel_diameter>${wheel_diameter}</wheel_diameter>
            <wheel_base>${wheel_base}</wheel_base>
            
            <!-- Limits -->
            <max_steer>0.6</max_steer>
            <max_speed>5.0</max_speed>

            <!-- Output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
        </plugin>
    </gazebo>

    <gazebo reference="laser_link">
        <sensor name="laser" type="ray">
            <update_rate>10</update_rate>
            <visualize>false</visualize>
            <ray>
                <scan><horizontal><samples>360</samples><min_angle>-${PI}</min_angle><max_angle>${PI}</max_angle></horizontal></scan>
                <range><min>0.05</min><max>2.0</max></range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros><namespace>/laser_controller</namespace><remapping>~/out:=scan</remapping></ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>
</robot>